### PR TITLE
Improve Greeting's Message

### LINKED ISSUE #4: FEATURE: Farmer greetings message UI improvement
### Have you updated the title?

- [X] I have updated the issue's title.

### As a...

user

### I can...

not be overwhelmed by the large font of the greeting text and also appreciate the artistic design of the message

### So that...

I can have an improved user experience

### Discussion

1. Having greeting messages in home page and common room page is a great idea in general, but currently the font size is too big and it's just a plain text with black background color.
2. Make the Greeting text slightly smaller, and maybe add movement, hover effect, animation, or gradient background color to make it more stand out.
3. The design is entirely up to the students.

### Acceptance Criteria

- [ ] Home page greeting text should have smaller font size than before as well as more sophisticated CSS effects.
- [ ] Play page greeting text should have smaller font size than before as well as more sophisticated CSS effects.

### Implementation Todos

Frontend:
- [ ] Home page greeting text should have smaller font size than before as well as more sophisticated CSS effects.
- [ ] Play page greeting text should have smaller font size than before as well as more sophisticated CSS effects.

Testing:
- [ ] Frontend: greeting text should have smaller font size and more sophisticated css effects, and students should write unit tests check those attributes.

### PR DESCRIPTION
**Pull request by AngelG261**
## Overview

In this PR, I added animation and color to the greetings message in both the Play page and the Home page.

## Screenshots (Optional)
Screenshot 2023-11-27 at 1 15 34 PM
image
Screenshot 2023-11-29 at 4 04 51 PM

## Linked Issues
Closes #4

### CODE REVIEW

**Review by jonathan-chen-opus — COMMENTED** [review]
Passed all the tests.
Color looks fine on both white background, but for some backgrounds it doesn't show up clearly.

There's a new line on playpage but that shouldn't be a problem.

**Comment by pconrad** [comment]
This is what it looks like against the actual backgrounds when deployed:

You can see this on the storybook: [Day](https://ucsb-cs156-f23.github.io/proj-happycows-f23-5pm-1/prs/26/storybook/?path=/story/pages-homepage--day) [Morning](https://ucsb-cs156-f23.github.io/proj-happycows-f23-5pm-1/prs/26/storybook/?path=/story/pages-homepage--morning)

howdy-farmer

The suggested  is to wrap the title in a component such as a `Card` (see: https://react-bootstrap.netlify.app/docs/components/cards/) and apply CSS styling so that there's a background.

**Comment by AngelG261** [comment]
image
how it looks while running on dokku

**Review by pconrad — APPROVED** [review]
LGTM, though it would be nicer if the card had some alpha transparency matching the other cards on the home page.

**Pull request merged**
