### PR TITLE
lli - Added UI changes and tests for Instructor Report Page

### LINKED ISSUE #14: FEATURE: UX/UI Improvements to Instructor Report page
# User Story

* As an instructor
* I can see an improved user interface on the instructor report page 
* So that I can I have an improved user experience

### Discussion

On the instructor report page, dollar amounts are not formatted as currency the way they are on the leaderboard page:

Compare:

image

vs.

image

We'd like dollar amounts formatted as currency, and we'd like other numbers right justified rather than left justified in their columns.

### Acceptance Criteria

- [ ] Dollar amounts on instructor report page are displayed as currency
- [ ] Other numbers are right justified.

### Implementation Todos

Should be a change to the react component that renders the instructor report page.

### PR DESCRIPTION
**Pull request by lukewli**
## Overview

In this PR, I have made changes to the Instructor Report Page UI so that the values for fields like Num Cows, Cows bought, etc, are right-justified and the Total Wealth field is now formatted as currency.

### Before
Screenshot 2023-11-20 at 2 45 56 PM
Screenshot 2023-11-20 at 5 29 38 PM

### After
Screenshot 2023-11-20 at 5 29 42 PM
Screenshot 2023-11-20 at 5 32 23 PM

## Validation

1. Download this branch and run the project.
3. Login for admin access and create/join a commons.
4. Create an instructor report for the common you've joined from the manage jobs page.
5. Check that the numbers are right-justified and that total wealth is formatted as a currency.

## Tests

- [ ] Frontend Unit tests (`npm test`) pass
- [ ] Frontend Test coverage (`npm run coverage`) 100%
- [ ] Frontend Mutation tests (`npx stryker run`) 100% 
- [ ] Frontend Linting (`npx eslint --fix src`) 

## Linked Issues
Closes #14

### CODE REVIEW

**Review by pconrad — COMMENTED** [review]
I like what you've done here, and we can merge this; but it would good to also take care of doing the same things for the top part of the report.  That would increase the point value from 5 to 10.

(or we can merge this, and you can do a separate 5 point PR for that other part.)

What I mean is this: can we also right justify the numeric values in this part of the report (and add the currency formatting to the dollar amount for starting balance?)

image

**Comment by lukewli** [comment]
Sure thing. I'll make changes to the other part of the report in this PR. Should I also right-justify the "id" field or leave that one as is?

**Comment by haroldmo** [comment]
this looks good.

**Review by pconrad — APPROVED** [review]
LGTM!

**Pull request merged**
